# Form implementation generated from reading ui file '.\layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 623)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(60, 40, 71, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 81, 61))
        self.label_2.setObjectName("label_2")
        self.imie = QtWidgets.QTextEdit(parent=Dialog)
        self.imie.setGeometry(QtCore.QRect(140, 50, 191, 41))
        self.imie.setObjectName("imie")
        self.nazwisko = QtWidgets.QTextEdit(parent=Dialog)
        self.nazwisko.setGeometry(QtCore.QRect(140, 110, 191, 41))
        self.nazwisko.setObjectName("nazwisko")
        self.rezerwuj = QtWidgets.QPushButton(parent=Dialog)
        self.rezerwuj.setGeometry(QtCore.QRect(170, 350, 151, 41))
        self.rezerwuj.setObjectName("rezerwuj")
        self.checkBox = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(60, 300, 171, 31))
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.wyswietl = QtWidgets.QLabel(parent=Dialog)
        self.wyswietl.setGeometry(QtCore.QRect(6, 420, 471, 191))
        self.wyswietl.setText("")
        self.wyswietl.setObjectName("wyswietl")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(60, 170, 317, 124))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.internista = QtWidgets.QRadioButton(parent=self.widget)
        self.internista.setObjectName("internista")
        self.verticalLayout.addWidget(self.internista)
        self.pediatra = QtWidgets.QRadioButton(parent=self.widget)
        self.pediatra.setObjectName("pediatra")
        self.verticalLayout.addWidget(self.pediatra)
        self.dermatolog = QtWidgets.QRadioButton(parent=self.widget)
        self.dermatolog.setObjectName("dermatolog")
        self.verticalLayout.addWidget(self.dermatolog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.label_2.setText(_translate("Dialog", "nazwisko"))
        self.rezerwuj.setText(_translate("Dialog", "rezerwuj"))
        self.checkBox.setText(_translate("Dialog", "wizyta prywatna"))
        self.label_3.setText(_translate("Dialog", "Do jakiego lekarza chcesz siię umówić"))
        self.internista.setText(_translate("Dialog", "Imternista"))
        self.pediatra.setText(_translate("Dialog", "Pediatra"))
        self.dermatolog.setText(_translate("Dialog", "Dermatolog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
